channels:
- conda-forge
dependencies:
- python=3.8.5
- pip<=20.2.4
- pip:
  - mlflow==2.17.2
  - cloudpickle==1.6.0
  - numpy==1.19.2
  - psutil==6.1.1
  - scikit-learn==1.1.1
  - scipy==1.5.2
name: mlflow-env
